[[redirects]]
from = "/upload"
to = "http://ec2-13-233-190-54.ap-south-1.compute.amazonaws.com:8000/upload"
status = 200
force = true

[[redirects]]
from = "/chat"
to = "http://ec2-13-233-190-54.ap-south-1.compute.amazonaws.com:8000/chat"
status = 200
force = true

