[[redirects]]
  from = "/upload"
  to = "${NEXT_PUBLIC_API_BASE_URL}/upload"
  status = 200
  force = true

[[redirects]]
  from = "/chat"
  to = "${NEXT_PUBLIC_API_BASE_URL}/chat"
  status = 200
  force = true
